"""领域常量：角色、状态与枚举。"""

# 查看数据的角色（决定脱敏策略），与参与案件处理的参与方不同。
ROLE_AGENT = "AGENT"            # 一线客服
ROLE_SUPERVISOR = "SUPERVISOR"  # 客服主管
ROLE_BANK = "BANK"              # 收单行人员
ROLE_MERCHANT = "MERCHANT"      # 商户
ROLE_TRANSLATOR = "TRANSLATOR"  # 翻译团队

ALL_ROLES = {
    ROLE_AGENT,
    ROLE_SUPERVISOR,
    ROLE_BANK,
    ROLE_MERCHANT,
    ROLE_TRANSLATOR,
}

# 案件外部参与方
PARTY_ACQUIRER = "ACQUIRER"
PARTY_MERCHANT = "MERCHANT"
PARTY_TRANSLATOR = "TRANSLATOR"
PARTY_INTERNAL = "INTERNAL"
EXTERNAL_PARTIES = {PARTY_ACQUIRER, PARTY_MERCHANT, PARTY_TRANSLATOR}

# 案件状态
CASE_OPEN = "OPEN"
CASE_EVIDENCE_REQUESTED = "EVIDENCE_REQUESTED"
CASE_IN_REVIEW = "IN_REVIEW"
CASE_ESCALATED = "ESCALATED"
CASE_RESOLVED = "RESOLVED"

TERMINAL_CASE_STATUSES = {CASE_RESOLVED}

# 最终结论
RESOLUTION_UPHELD = "UPHELD"                # 争议成立
RESOLUTION_REJECTED = "REJECTED"            # 争议驳回
RESOLUTION_PARTIAL_REFUND = "PARTIAL_REFUND"  # 部分退款了结
RESOLUTION_WITHDRAWN = "WITHDRAWN"          # 客户撤回

# 证据请求状态
EV_REQUESTED = "REQUESTED"
EV_SUBMITTED = "SUBMITTED"
EV_ACCEPTED = "ACCEPTED"
EV_REJECTED = "REJECTED"

# 退款状态
RF_PROPOSED = "PROPOSED"
RF_APPROVED = "APPROVED"
RF_SENT_TO_BANK = "SENT_TO_BANK"
RF_CONFIRMED = "CONFIRMED"
RF_REJECTED = "REJECTED"
REFUND_KIND_PARTIAL = "PARTIAL"
REFUND_KIND_FULL = "FULL"

# 翻译版本状态
TR_REQUESTED = "REQUESTED"
TR_IN_PROGRESS = "IN_PROGRESS"
TR_DELIVERED = "DELIVERED"
TR_SUPERSEDED = "SUPERSEDED"

# 客户撤回状态
WD_REQUESTED = "REQUESTED"
WD_CONFIRMED = "CONFIRMED"
WD_REJECTED = "REJECTED"

# 外部请求状态
REQ_PENDING = "PENDING"
REQ_DISPATCHED = "DISPATCHED"
REQ_ACKNOWLEDGED = "ACKNOWLEDGED"
REQ_FAILED = "FAILED"
UNFINISHED_REQUEST_STATUSES = {REQ_PENDING, REQ_DISPATCHED}

# 时限状态
DL_OPEN = "OPEN"
DL_MET = "MET"
DL_BREACHED = "BREACHED"

# 转派类型
HANDOVER_TRANSFER = "TRANSFER"
HANDOVER_ESCALATION = "ESCALATION"

# 通知状态
NTF_PENDING = "PENDING"
NTF_DELIVERED = "DELIVERED"

# 回执类型
RECEIPT_EVIDENCE_ACK = "EVIDENCE_ACK"
RECEIPT_REFUND = "REFUND"
RECEIPT_CHARGEBACK = "CHARGEBACK"
RECEIPT_GENERIC = "GENERIC"
